# Use this to enable local_backend
local_backend: true

# Backend configuration 
backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
show_preview_links: true
media_folder: static/img
public_folder: /img
collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: 'Draft'
        name: 'draft'
        widget: 'boolean'
        default: false
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Last Modified Date'
        name: 'lastmod'
        widget: 'datetime'
        required: false
      - label: 'Author'
        name: 'author'
        widget: 'string'
        required: false
      - label: 'Author Link'
        name: 'authorlink'
        widget: 'string'
        required: false
      - label: 'Cover'
        name: 'cover'
        widget: 'image'
        required: false
      - label: 'Categories'
        name: 'categories'
        widget: 'list'
        summary: '{{fields.category}}'
        field:
          label: 'Category'
          name: 'category'
          widget: 'string'
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        summary: '{{fields.tag}}'
        field:
          label: 'Tag'
          name: 'tag'
          widget: 'string'
      - label: 'Disable Last Modified Date'
        name: 'nolastmod'
        widget: 'boolean'
        default: false

      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  - name: 'about'
    label: 'About'
    folder: 'content/about'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: 'Draft'
        name: 'draft'
        widget: 'boolean'
        default: false
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'

      - label: 'Body'
        name: 'body'
        widget: 'markdown'
